package main.utils;

public class Constantes {
    public static String PATH_VIEWS_FXML = "/main/views/fxml/";
    public static String PATH_IMAGES = "/assets/images/";
    public static String PATH_FILES = "/assets/files/";
    public static String FORM_HOME = PATH_VIEWS_FXML + "Home.fxml";
    public static String FORM_BASE = PATH_VIEWS_FXML + "Base.fxml";
    public static String FORM_DESPESAS = PATH_VIEWS_FXML + "Despesas.fxml";
    public static String FORM_DOACOES = PATH_VIEWS_FXML + "Doacoes.fxml";
    public static String FORM_TAREFAS = PATH_VIEWS_FXML + "Tarefas.fxml";
    public static String FORM_EQUIPE = PATH_VIEWS_FXML + "Equipe.fxml";
    public static String FORM_AUDITORIAS = PATH_VIEWS_FXML + "Auditorias.fxml";
    public static String FORM_ANIMAL_DETALHES = PATH_VIEWS_FXML + "AnimalDetalhes.fxml";
    public static String CARD_ANIMAL = PATH_VIEWS_FXML + "AnimalCardv2.fxml";
    public static String CARD_BANCO = PATH_VIEWS_FXML + "ImportarBanco.fxml";
    public static String CARD_ADICIONAR_ANIMAL = PATH_VIEWS_FXML + "AdicionarAnimal.fxml";
    public static String CARD_ADICIONAR_DOACAO = PATH_VIEWS_FXML + "AdicionarDoacao.fxml";
    public static String CARD_ADICIONAR_DESPESA = PATH_VIEWS_FXML + "AdicionarDespesa.fxml";
    public static String CARD_ADICIONAR_PROCEDIMENTO = PATH_VIEWS_FXML + "AdicionarProcedimento.fxml";
    public static String CARD_DESPESA = PATH_VIEWS_FXML + "Despesa.fxml";
    public static String CARD_AUDITORIA = PATH_VIEWS_FXML + "Auditoria.fxml";
    public static String CARD_DOACAO = PATH_VIEWS_FXML + "Doacao.fxml";
    public static String CARD_TAREFA = PATH_VIEWS_FXML + "Tarefa.fxml";
    public static String CARD_VOLUNTARIO = PATH_VIEWS_FXML + "VoluntarioV2.fxml";
    public static String CARD_ADICIONAR_VOLUNTARIO = PATH_VIEWS_FXML + "AdicionarVoluntario.fxml";
    public static String TOOGLE_BUTTON = PATH_VIEWS_FXML + "ToogleButtonv2.fxml";
    public static String TOOGLE_BUTTON_SHORT = PATH_VIEWS_FXML + "ToogleButtonv2Short.fxml";
    public static String CARD_PROCEDIMENTO = PATH_VIEWS_FXML + "Procedimentov2.fxml";
    public static String DIALOG_CADASTRAR_ANIMAL = PATH_VIEWS_FXML + "CadastrarAnimal.fxml";
    public static String DIALOG_CADASTRAR_VOLUNTARIO = PATH_VIEWS_FXML + "CadastrarVoluntario.fxml";
    public static String DIALOG_CADASTRAR_TAREFA = PATH_VIEWS_FXML + "CadastrarTarefa.fxml";
    public static String DIALOG_CADASTRAR_PROCEDIMENTO = PATH_VIEWS_FXML + "CadastrarProcedimento.fxml";
    public static String DIALOG_CADASTRAR_DOACAO = PATH_VIEWS_FXML + "CadastrarDoacao.fxml";
    public static String DIALOG_CADASTRAR_DESPESA = PATH_VIEWS_FXML + "CadastrarDespesa.fxml";
    public static String DIALOG_CADASTRAR_ADOCAO = PATH_VIEWS_FXML + "CadastrarAdocao.fxml";
    public static String DIALOG_MENSAGEM = PATH_VIEWS_FXML + "Mensagem.fxml";
    public static String DIALOG_FILTRAR_ANIMAL = PATH_VIEWS_FXML + "FiltrarAnimal.fxml";
    public static String DIALOG_REMOVER = PATH_VIEWS_FXML + "Remover.fxml";
    public static String PATH_DATA_BASE = PATH_FILES + "scripts.sql";
}
